# Generated by Django 3.1.6 on 2021-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freizeittipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, verbose_name='Titel')),
                ('age_from', models.IntegerField(default=0, verbose_name='Geeignet für ein Alter von')),
                ('age_to', models.IntegerField(default=18, verbose_name='bis')),
                ('freizeittipp_image', models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/freizeittipps/', verbose_name='Freizeittipp-Bild')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('hp_link', models.URLField(default='blank', verbose_name='Homepage')),
                ('tel', models.CharField(default='blank', max_length=32, verbose_name='Telefon-Nr')),
                ('email', models.EmailField(default='blank', max_length=264)),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_current', models.DateField(auto_now=True, verbose_name='Zuletzt geändert am')),
                ('categories', models.ManyToManyField(default='blank', help_text='Kategorie angeben', to='category.Category')),
                ('tags', models.ManyToManyField(default='blank', help_text='Tags angeben', to='category.Tag')),
            ],
        ),
    ]
