# Generated by Django 3.1.6 on 2021-02-18 11:10

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('category', '0002_auto_20190103_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Salzburg', max_length=126, verbose_name='Stadt')),
                ('postal_code', models.PositiveIntegerField(default='5020', verbose_name='PLZ')),
                ('street', models.CharField(max_length=126, verbose_name='Strasse, Nr')),
                ('country', models.CharField(default='Österreich', max_length=126, verbose_name='Land')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_link', models.URLField(default='blank', verbose_name='Homepage')),
                ('tel', models.CharField(default='blank', max_length=32, verbose_name='Telefon-Nr')),
                ('email', models.EmailField(default='blank', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Freizeittipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264, verbose_name='Titel')),
                ('age_from', models.IntegerField(default=0, verbose_name='Geeignet für ein Alter von')),
                ('age_to', models.IntegerField(default=18, verbose_name='bis')),
                ('freizeittipp_image', models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/freizeittipps/', verbose_name='Freizeittipp-Bild')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht?')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_current', models.DateField(auto_now=True, verbose_name='Zuletzt geändert am')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_freizeittipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ManyToManyField(default='blank', help_text='Tags angeben', to='category.Tag')),
                ('tag_taggit', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Schlagworte_taggit')),
            ],
        ),
        migrations.CreateModel(
            name='Category_freizeittipp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(default='blank', help_text='Kategorie angeben', to='category.Category')),
            ],
        ),
    ]
