# Generated by Django 3.1.6 on 2021-02-21 10:20

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('freizeittipp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='category_freizeittipp',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='tag_freizeittipp',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag_freizeittipp',
            name='tag_taggit',
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='categories',
            field=models.ManyToManyField(default='blank', help_text='Kategorie angeben', to='category.Category'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='city',
            field=models.CharField(default='Salzburg', max_length=126, verbose_name='Stadt'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='country',
            field=models.CharField(default='Österreich', max_length=126, verbose_name='Land'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='email',
            field=models.EmailField(default='blank', max_length=264),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='hp_link',
            field=models.URLField(default='blank', verbose_name='Homepage'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='postal_code',
            field=models.PositiveIntegerField(default='5020', verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='street',
            field=models.CharField(default='blank', max_length=126, verbose_name='Strasse, Nr'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='tag',
            field=models.ManyToManyField(default='blank', help_text='Tags angeben', to='category.Tag', verbose_name='Schlagwort_category'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='tag_taggit',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Schlagworte_taggit'),
        ),
        migrations.AddField(
            model_name='freizeittipp',
            name='tel',
            field=models.CharField(default='blank', max_length=32, verbose_name='Telefon-Nr'),
        ),
        migrations.DeleteModel(
            name='Category_freizeittipp',
        ),
        migrations.DeleteModel(
            name='Tag_freizeittipp',
        ),
    ]
