# Generated by Django 3.1.6 on 2021-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('freizeittipp', '0002_auto_20210221_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freizeittipp',
            name='categories',
            field=models.ManyToManyField(blank='True', help_text='Kategorie angeben', null='True', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='freizeittipp',
            name='hp_link',
            field=models.URLField(blank='True', null='True', verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='freizeittipp',
            name='street',
            field=models.CharField(blank='True', max_length=126, null='True', verbose_name='Strasse, Nr'),
        ),
        migrations.AlterField(
            model_name='freizeittipp',
            name='tag',
            field=models.ManyToManyField(blank='True', help_text='Tags angeben', null='True', to='category.Tag', verbose_name='Schlagwort_category'),
        ),
        migrations.AlterField(
            model_name='freizeittipp',
            name='tel',
            field=models.CharField(blank='True', max_length=32, null='True', verbose_name='Telefon-Nr'),
        ),
    ]
