# Generated by Django 3.1.6 on 2021-02-21 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freizeittipp', '0003_auto_20210221_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freizeittipp',
            name='freizeittipp_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='TippImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='static/images/freizeittipps/')),
                ('freizeittipp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='freizeittipp.freizeittipp')),
            ],
        ),
    ]
