# Generated by Django 3.1.6 on 2021-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freizeittipp', '0004_auto_20210221_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freizeittipp',
            name='freizeittipp_image',
            field=models.ImageField(default='static/images/no-img.jpg', upload_to='static/images/freizeittipps/', verbose_name='Freizeittipp-Bild'),
        ),
        migrations.DeleteModel(
            name='TippImage',
        ),
    ]
