# Generated by Django 3.1.6 on 2021-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('freizeittipp', '0005_auto_20210221_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freizeittipp',
            name='categories',
            field=models.ManyToManyField(blank='True', help_text='Kategorie angeben', to='category.Category'),
        ),
        migrations.AlterField(
            model_name='freizeittipp',
            name='tag',
            field=models.ManyToManyField(blank='True', help_text='Tags angeben', to='category.Tag', verbose_name='Schlagwort_category'),
        ),
    ]
